#!/usr/bin/env bash
# SkyTrack Portal v2 first-boot bootstrap.
# Runs once via the skytrack-firstboot.service oneshot.
#
# Steps:
#   1. Create /var/lib/skytrack and /var/log/skytrack with sane perms
#   2. Generate or load the device ID
#   3. Run database migrations (creates skytrack.db with schema v1)
#   4. Write /opt/skytrack/static/splash/device_id.js so the file:// splash
#      can display the device ID before skytrack-app is running
#   5. Drop a marker file so this never reruns
#
# Uses /opt/skytrack/.venv/bin/python3 explicitly — NEVER the system python3,
# which would miss pyyaml, flask, etc. and silently break firstboot.

set -euo pipefail

REPO_DIR="${SKYTRACK_REPO_DIR:-/opt/skytrack}"
DATA_DIR="${SKYTRACK_DATA_DIR:-/var/lib/skytrack}"
LOG_DIR="${SKYTRACK_LOG_DIR:-/var/log/skytrack}"
SKYTRACK_USER="${SKYTRACK_USER:-skytrack}"
MARKER="$DATA_DIR/.firstboot-done"
VENV_PY="$REPO_DIR/.venv/bin/python3"
SPLASH_DIR="$REPO_DIR/static/splash"
DEVICE_JS="$SPLASH_DIR/device_id.js"

if [[ -f "$MARKER" ]]; then
  echo "firstboot: already complete (marker present)"
  exit 0
fi

if [[ ! -x "$VENV_PY" ]]; then
  echo "firstboot: ERROR — $VENV_PY is missing or not executable" >&2
  echo "firstboot:         run install.sh first" >&2
  exit 1
fi

echo "firstboot: creating directories"
mkdir -p "$DATA_DIR" "$LOG_DIR" "$DATA_DIR/backups" "$DATA_DIR/ota-workspace"
install -d -m 0700 -o "$SKYTRACK_USER" -g "$SKYTRACK_USER" "$DATA_DIR/.ssh"
if [[ ! -f "$DATA_DIR/.ssh/known_hosts" ]]; then
  : > "$DATA_DIR/.ssh/known_hosts"
  chown "$SKYTRACK_USER:$SKYTRACK_USER" "$DATA_DIR/.ssh/known_hosts"
  chmod 0600 "$DATA_DIR/.ssh/known_hosts"
fi
chown -R "$SKYTRACK_USER:$SKYTRACK_USER" "$DATA_DIR" "$LOG_DIR" 2>/dev/null || true

mkdir -p "$SPLASH_DIR"

echo "firstboot: bootstrapping device ID + database"
cd "$REPO_DIR"
SKYTRACK_REPO_DIR="$REPO_DIR" \
SKYTRACK_DATA_DIR="$DATA_DIR" \
"$VENV_PY" - <<'PY'
import os
import sys
import json

sys.path.insert(0, os.environ.get('SKYTRACK_REPO_DIR', '/opt/skytrack'))

import device_id
import db

identity = device_id.get_or_create_device_id()
print(f"device_id: {identity['device_id']} ({identity.get('hw_source')})")

db.migrate()
print(f"schema: v{db.current_version()}")

# Write the file:// splash device-ID shim. The splash page loads this file
# via <script src="device_id.js"></script> so it can render the device-ID
# pill BEFORE the backend is running — we can't fetch /api/device before
# skytrack-app is listening. This is the single source of truth for the
# splash's device identity.
splash_js = os.path.join(
    os.environ.get('SKYTRACK_REPO_DIR', '/opt/skytrack'),
    'static', 'splash', 'device_id.js',
)
os.makedirs(os.path.dirname(splash_js), exist_ok=True)
with open(splash_js, 'w') as f:
    f.write(
        '// Generated by scripts/firstboot.sh — do not edit.\n'
        f'window.SKYTRACK_DEVICE_ID = {json.dumps(identity["device_id"])};\n'
    )
print(f"splash device_id.js: {splash_js}")
PY

# Make sure the splash directory (including device_id.js) is world-readable
# so the skytrack-kiosk user's Chromium can load it via file://.
chmod 0755 "$SPLASH_DIR" 2>/dev/null || true
chmod 0644 "$DEVICE_JS" 2>/dev/null || true

echo "firstboot: writing marker"
date -u +%FT%TZ > "$MARKER"
echo "firstboot: complete"
